---
# This is intended to be included in main.yml in this directory.
# Its purpose is to provide a standard template for migrating the contents
# of a directory from one location to another.
#
# It expects the following variables: `src` (the original location) and
# `dest` (the new location).
- name: rsync {{ src }} to {{ dest }}.
  shell: rsync -auq {{ src }} {{ dest }}
  args:
    creates: '{{ dest }}'
    shell: /bin/bash

- name: Remove the {{ src }} directory.
  file:
    path: '{{ src.rstrip("/") }}'
    state: absent

- name: Temporarily sync {{ src }} to {{ dest }}, giving later configuration a chance to update.
  file:
    path: '{{ src.rstrip("/") }}'
    src: '{{ dest }}'
    state: link
  notify: Remove {{ src }} symlink.
