---

- name: deploy config file for rsyslogd
  copy: src=51-awx.conf dest=/etc/rsyslog.d/51-awx.conf
  notify: restart rsyslogd

- name: If Ansible does not provide a system UUID, get a random one.
  script: random_uuid.py
  connection: local
  sudo: no
  when: ansible_product_uuid.lower() in ('', 'na')
  register: system_uuid
  changed_when: False

- name: Write a ha.conf file to /etc/tower that contains the system UUID.
  template:
    dest: /etc/tower/conf.d/ha.py
    force: no
    group: awx
    mode: 0644
    owner: awx
    src: ha.py

- name: Register the primary instance in the database.
  shell: awx-manage register_instance --timid --{{ primacy }} --hostname="{{ inventory_hostname }}"
  args:
    executable: /bin/bash
  sudo_user: awx
  register: register_instance
  changed_when: "'changed: True' in register_instance.stdout"
  when: primacy == 'primary'

- name: Register the secondary instances in the database.
  shell: awx-manage register_instance --timid --{{ primacy }} --hostname="{{ inventory_hostname }}"
  args:
    executable: /bin/bash
  sudo_user: awx
  register: register_instance
  changed_when: "'changed: True' in register_instance.stdout"
  when: primacy == 'secondary'
