---
# Tasks to install required packages for awx

- include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'           # Ubuntu-12.04, Ubuntu-14.04
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'     # Ubuntu-12, Ubuntu-14
        - '{{ ansible_distribution }}.yml'                                              # Ubuntu
        - 'default.yml'
      paths: '../vars'

- name: install ubuntu awx apt repository
  template: src=awx_repo.j2 dest=/etc/apt/sources.list.d/awx_repo.list

- name: Remove Django if installed via. apt.
  apt:
    name: python-django
    state: absent

- name: Install pip.
  apt:
    name: python-pip
    state: present
    update_cache: yes

- name: Install django 1.6.x using pip.
  pip:
    name: django>=1.6.7,<1.7
    state: latest

- name: install apt repository keys
  apt_key:
    url: '{{ item }}'
  when: apt_keys is defined
  with_items: apt_keys

- name: install apt repositories
  apt_repository:
    repo: '{{ item }}'
  when: apt_repos is defined
  with_items: apt_repos

- name: Remove obsolete packages.
  apt:
    name: '{{ item }}'
    state: absent
  with_items:
    - rabbitmq-server

- name: A secret key may already exist; test if it does.
  stat:
    path: /etc/tower/SECRET_KEY
  register: secret_key

- name: If a secret key already exists, read it into memory.
  slurp:
    src: /etc/tower/SECRET_KEY
  register: sk_content
  when: secret_key.stat.exists

  # NOTE: The 'apt' module doesn't support installing packages with a wildcard
  # ('*').  Refer to https://github.com/ansible/ansible-modules-core/pull/28.
  # A fix is included in ansible-1.8. Older versions of ansible will call
  # 'apt-get' directly.
- name: install awx package with the apt module
  apt: name='{{tower_package_deb}}' update_cache=yes force=yes state=present
  when: ansible_version is defined and ansible_version.full|version_compare('1.8', '>=')
  register: apt_install

- name: update apt cache when using the apt-get command
  apt: update_cache=yes
  when: apt_install|skipped

- name: install awx package with the apt-get command
  command: "apt-get --allow-unauthenticated -y install '{{tower_package_deb}}'"
  changed_when: "'0 upgraded, 0 newly installed' not in result.stdout"
  register: result
  when: apt_install|skipped

- name: Restore the secret key.
  copy:
    content: "{{ sk_content.content.decode('base64') }}"
    dest: /etc/tower/SECRET_KEY
    force: yes
  when: secret_key.stat.exists

- name: remove ubuntu awx apt repository
  file: path=/etc/apt/sources.list.d/awx_repo.list state=absent

- name: update apt cache
  apt: update_cache=yes
